### ISSUE TITLE
Glassfish lifecycle exception

### ISSUE THREAD

**Issue by akyekth** [javaee/glassfish#21727]
Hi project deploying in glassfish 4.1.1 server while deploying i got the below exception.

If any one got the below exception Please help me.

Payara 4.1|javax.enterprise.system.core|_ThreadID=94;_ThreadName=admin-thread-pool(6);_TimeMillis=1493383149301;_LevelValue=1000;|Exception while deploying the app [hopsworks-api] : The lifecycle method [stop] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void io.airlift.http.server.HttpServer.stop() throws java.lang.Exception] of type [METHOD]
The lifecycle method [stop] must not throw a checked exception. Related annotation information: annotation [@javax.annotation.PreDestroy()] on annotated element [public void io.airlift.http.server.HttpServer.stop() throws java.lang.Exception] of type [METHOD]
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:375)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.process(AnnotationProcessorImpl.java:383)
	at org.glassfish.apf.impl.AnnotationProcessorImpl.processAnnotations(AnnotationProcessor

Thanks in Advance
Aruna

**Comment by delabassee** [comment]
The exception says it's Payara not GF!
