### ISSUE TITLE
Integrate JSR 375 RI (soteria) in glassfish 5.

### ISSUE THREAD

**Issue by sameer-pandit** [javaee/glassfish#21735]
Integrate JSR 375 RI [soteria](https://github.com/javaee-security-spec/soteria) in GlassFish.

**Comment by keilw** [comment]
@wmhopkins @arjantijms Any idea, when this can be in Glassfish?

**Comment by arjantijms** [comment]
@keilw The integration work should be trivial; just putting the compiled module in /modules of GF.

There are (or were) a number of bugs in GF5 though which cause a few tests to fail, for instance the custom principal doesn't arrive at the user code. All those bugs have been fixed in Payara though.

**Comment by keilw** [comment]
@arjantijms Can they be merged back into GF5 without problems from Payara?;-)

**Comment by arjantijms** [comment]
@keilw 

Anybody can create a PR from Payara subject to usual open source licensing rules ;)
