### ISSUE TITLE
A local packaged file is deleted when deploying from the web console.

### ISSUE THREAD

**Issue by hs536** [javaee/glassfish#21760]
**Issue:** 
A local packaged file is deleted when deploying from the web console.

**Reproduce Issue:**
1. Create a local packaged file. (Any kind of local packaged file can be used to reproduce the issue. For example, I have written a very simple Hello World servlet and created helloworld.war. )
2. Deploy it from the Web Admin Console by  "Local Packaged File or Directory That Is Accessible From the GlassFish Server".
3. Glassfish deletes the user’s local packaged file when deployment is finished.

**Cause of Issue:**
WoodstockHandler#deleteFileFromTempDir() deletes a file which exists in the path passed as an argument.
This method was added by the revision 63833 to delete a temporary file in a temporary directory when a package file is uploaded from the web console.
However, this method is also called when a local packaged file is deployed from the web console.
The local packaged file is deleted as a result.

**Related Tracker:**
CLONE -Deployment from Web Console: temporary files are not deleted
https://java.net/jira/browse/GLASSFISH-21028

**Affected Versions:**
glassfish-4.1.2 (takes the revision 63833 in the package)

**Comment by hs536** [comment]
**Related Tracker (GitHub):**
#21028

**Comment by srinivaskrishnan** [comment]
The fix is when deleting the file check if this in the glassfish server path, if not do not delete the file
