### ISSUE TITLE
Integrate servlet-spec#176

### ISSUE THREAD

**Issue by edburns** [javaee/glassfish#21773]
Tracker to integrate servlet-spec#176.

**Comment by edburns** [comment]
fixes for this are in < https://github.com/edburns/glassfish/tree/SERVLETMAPPING-21773 >.

**Comment by edburns** [comment]
Diff for SERVLETMAPPING-21773 at < https://github.com/edburns/glassfish/commit/6df2889211cf508d6929b523b2fa389fa2360c66.diff >.

**Comment by edburns** [comment]
Feel free to use this diff or not, @shingwaichan.  Thanks.

**Comment by edburns** [comment]
Test changes at < https://github.com/edburns/glassfish/commit/66e274e9894a95a51aa395643336235b8e2d1977.diff > @shingwaichan

**Comment by shingwaichan** [comment]
The javax.servlet-api 4.0.0-b06, which contains servlet-spec#176 and other changes, has been integrated in https://github.com/javaee/glassfish/pull/21784
