### ISSUE TITLE
Reusable LICENSE URL

### ISSUE THREAD

**Issue by keilw** [javaee/glassfish#21777]
Many Java EE projects, especially those under org.glassfish referenced the license on https://glassfish.java.net/public/CDDL+GPL_1_1.html (now a dead link)
Is https://javaee.github.io/glassfish/LICENSE now the correct equivalent after moving to GitHub?

Or is https://oss.oracle.com/licenses/CDDL+GPL-1.1 the better one?

**Comment by bshannon** [comment]
To match the conventions at GitHub, there's a copy of the license in each repository.
References to the license from within the repository will typically refer to the copy that's
in the repository.  References to the license in other contexts would be better to refer
to the (new) canonical location at https://oss.oracle.com/licenses/CDDL+GPL-1.1.

**Comment by keilw** [comment]
I saw that in projects like jsonp. Thanks for the clarification.
