### ISSUE TITLE
Query: Removing the contents in particular glassfish directories

### ISSUE THREAD

**Issue by Maddy-2999** [javaee/glassfish#21814]
Hi Team, 

Is it okay to clear the contents of "osgi-cache", "generated/applications/" when Glassfish is online?
Or it shall be done only when Glassfish is offline?

**Comment by yaminikb** [comment]
No, it is not ok to delete these directories when server is running since it can cause unpredictable behaviour.

Madhan, please join https://javaee.groups.io/g/glassfish for posting queries. GitHub issue tracker is only for bugs.
