### ISSUE TITLE
“Confidential” property is not masked in “Edit Admin Object Resource” of Admin Console (Bug #19480 has not been fixed)

### ISSUE THREAD

**Issue by tak-9** [javaee/glassfish#21837]
## Environment Details
* GlassFish Version (and build number): Glassfish 5.0-b07
* JDK version: 1.8.0_112
* OS: Windows 2012 R2

----------

## Problem Description
This bug (#19480) has not been fixed completely. https://github.com/javaee/glassfish/issues/19480
This bug has been fixed in "New Admin Object Resource". The "Confidential" property is not displayed (masked with dot characters). However, the "Confidential” property is visible in "Edit Admin Object Resource". This bug has not been fixed in "Edit Admin Object Resource". 

## Steps to reproduce
1. Deploy the attached test application.
2. Open Resources>Connectors>Admin Object Resources in the Admin Console. 
3. Click “New” button to open the “New Admin Object Resource”. 
4. Choose “genericra” for the Resource Adapter and enter text in “DestinationGNPassword”. Confirm that the texts for this field are masked.  Enter the rest of the information and click “OK”.
5. Open the Admin Object Resource you have just created in the previous step.  DestinationGNPassword is not masked. (This is a bug.)

## Fix

```
 .../admingui/jca/src/main/resources/adminObjectEdit.jsf          | 9 +++++++--
 1 file changed, 7 insertions(+), 2 deletions(-)

diff --git a/main/appserver/admingui/jca/src/main/resources/adminObjectEdit.jsf b/main/appserver/admingui/jca/src/main/resources/adminObjectEdit.jsf
index 0adc4561fb..83bd7aa6ed 100644
--- a/main/appserver/admingui/jca/src/main/resources/adminObjectEdit.jsf
+++ b/main/appserver/admingui/jca/src/main/resources/adminObjectEdit.jsf
@@ -100,7 +100,6 @@
     setPageSessionAttribute(key="convertToFalseList" value={"enabled"});
     setPageSessionAttribute(key="skipAttrsList", value={"jndiName"});
     gf.restRequest(endpoint="#{pageSession.selfUrl}/property.json" method="GET" result="#{requestScope.propTable}");
-    setPageSessionAttribute(key="tableList" value="#{requestScope.propTable.data.extraProperties.properties}");
     
     //set the following for including buttons.inc
     setPageSessionAttribute(key="edit" value="#{true}" );
@@ -131,6 +130,12 @@
             mapPut(map="#{pageSession.valueMap}" key="resType" value="#{requestScope.resourceTypes[0]}");
         }
         mapPut(map="#{pageSession.attrsMap}" key="adminObjectInterface" value="#{pageSession.valueMap.resType}");
+        //To get the admin-object-config-props
+        gf.restRequest(endpoint="#{sessionScope.REST_URL}/resources/get-admin-object-config-properties"
+                           attrs="#{pageSession.attrsMap}"
+                           method="GET"
+                           result="#{requestScope.result}");
+        gf.buildConfidentialPropsTable(propsMaps="#{requestScope.propTable.data.extraProperties.properties}", confidentialList="#{requestScope.result.data.extraProperties.confidentialConfigProps}",   result="#{pageSession.tableList}" hasConfidentialProps="#{pageSession.hasConfidential}");
         //To get the get-admin-object-class-names
         gf.restRequest(endpoint="#{sessionScope.REST_URL}/resources/get-admin-object-class-names"
                        attrs="#{pageSession.attrsMap}"
@@ -157,7 +162,7 @@
     "<br><br>
     
 #include "/jca/adminObjectAttr.inc"
-#include "/common/shared/propertyDescTable.inc"
+#include "/common/resourceNode/confidentialPropsTable.inc"
     
     <sun:hidden id="helpKey" value="$resource{help_jca.adminObjectEdit}" />
 </sun:form>

```

[genericra.zip](https://github.com/javaee/glassfish/files/1073492/genericra.zip)

**Comment by sumauppa** [comment]
zip file is not able to deploy. Could you please recheck and upload the application.

**Comment by tak-9** [comment]
@sumauppa 
I have tried it again and it works. Here's what I did to confirm it. 
1. Download the file. https://github.com/javaee/glassfish/files/1073492/genericra.zip 
2. Extract genericra.zip 
3. Use Glassfish 5.0 b07. Open Admin Console.  Choose Applications from the tree. Click Deploy button. Click Browse button and choose the extracted file (genericra.rar) by the file selection dialog box.  
4. Click OK. 
Please let me know if you still can't deploy it. Thank you.

**Comment by sumauppa** [comment]
It worked and able to reproduce the issue. Working on the fix.

**Comment by yaminikb** [comment]
@tak-9 We really appreciate you trying out GlassFish and reporting issues. Would you be interested on contributing directly to GlassFish? You are welcome to sign the [OCA](http://www.oracle.com/technetwork/community/oca-486395.html) and start raising pull requests.

**Comment by tak-9** [comment]
@yaminikb I have asked our company’s management team about signing the OCA. They told me that the management will be sending the OCA forms on behalf as there are several other people need to sign it as well. As it will be sent through the company’s management team, please give us sometime before I can sign and send it to you. Thank you for waiting.
