### ISSUE TITLE
Async listener onTimeout calling complete causes NPE

### ISSUE THREAD

**Issue by jjsnyder** [javaee/glassfish#21847]
## Environment Details
* GlassFish Version (and build number): master as of 20170614
* JDK version: 1.8.0-121
* OS: linux
* Database: n/a

----------

## Problem Description
If an AsyncListener's onTimeout method calls complete on the asyn context glassfish will produce a NPE in the AsyncContextImpl#notifyAsyncListeners in the finally block where the WeldListener.requestDestroyed is called.  You should see that the second time this code is executed the origRequest member variable is null which will cause a NPE when the event is attempted to be built.  The reason is that the async listener in the app has its onTimeout method called and the onTimeout is calling complete on the async context.  This is causing notifyAsyncListeners to be called again.  If you put a breakpoint on the AsyncContextImpl#clear method you will see that it sets the origRequest member variable to null when complete is called.  This is causing the NPE to occur. 

## Steps to reproduce
Extract the war from the attached jar at /web/target/async.war and drop it into autodeploy directory of running glassfish.  Set a breakpoint at AsyncContextImpl#notifyAsyncListeners in the finally block where the WeldListener.requestDestroyed is called.  To make it happen execute http://localhost:8080/async/async
Note that the NPE is swallowed so you won't see it unless you set a breakpoint. 

## Impact of Issue
Causes failure in CDI 2.0 TCK

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by jjsnyder** [comment]
I am unable to attach the reproducer app.  Please contact me and I will email it to you.

**Comment by shingwaichan** [comment]
The following is the scenario of calling complete() inside a timeout.
-> weld.requestInitialized
-->  timeout event
--->  weld.requestInitialized
---->  complete event
--->  weld.requestDestroyed
-> weld.requestDestroyed

There are two issues here. First, the complete() closes the response object and recycle/cleanup internal objects of AsyncContextImpl. Second, the second (also, the first) weld.requestDestroyed will invoke the request.getAttribute().
