### ISSUE TITLE
A thread pool with a special character cannot be deleted. 

### ISSUE THREAD

**Issue by tak-9** [javaee/glassfish#21851]
## Environment Details
* GlassFish Version (and build number):Glassfish 5.0-b07
* JDK version:1.8.0_112
* OS:Windows 2012 R2

----------

## Problem Description
A thread pool with a special character (test; or test/) cannot be deleted. 

## Steps to reproduce
1. Navigate to Configurations > [config] > Thread Pools
2. Click "New..." and create a new thread pool, named "test/" or "test;"
=> After saving, the Thread Pools page shows the new thread pool in the table
3. Select the checkbox for the new thread pool
4. Click "Delete" and then "OK" in the popup dialogue to proceed
=> The new thread pool doesn't get deleted, and remains in the table.

## Fix
The thread pool name is not URL-encoded for the config DELETE endpoint used in RestApiHandlers.deleteConfigCascade.
Changed gf.deleteConfigCascade to encode the REST request URL in the same way as gf.deleteCascade.

````
diff --git "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\RestApiHandlers-23e8e06.001.java" "b/C:\\gf5\\glassfish\\main\\appserver\\admingui\\common\\src\\main\\java\\org\\glassfish\\admingui\\common\\handlers\\RestApiHandlers.java"
index a31ab05b87..8baa594695 100644
--- "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\RestApiHandlers-23e8e06.001.java"
+++ "b/C:\\gf5\\glassfish\\main\\appserver\\admingui\\common\\src\\main\\java\\org\\glassfish\\admingui\\common\\handlers\\RestApiHandlers.java"
@@ -329,7 +329,7 @@ public class RestApiHandlers {
 
             for ( Map oneRow : selectedRows) {
                 try{
-                    String endpoint = prefix + "/" + oneRow.get(id);
+                    String endpoint = prefix + "/" + URLEncoder.encode((String) oneRow.get(id), "UTF-8");
                     RestUtil.restRequest(endpoint, payload, "DELETE",null, false);
                 }catch (Exception ex){
                     GuiUtil.getLogger().severe(
````

**Comment by delabassee** [comment]
@tak-9 if you haven't done it yet, could you please sign the Contributor Agreement?
See http://www.oracle.com/technetwork/community/oca-486395.html
