### ISSUE TITLE
Empty stack traces in a remote invocation's exception 

### ISSUE THREAD

**Issue by satoyoshiki** [javaee/glassfish#21945]
## Environment Details
* GlassFish 4.1
----------

## Problem Description

Stack traces are not stored in an exception thrown from EJB remote invocations.  This issue can be observed only in the case that InvocationTargetException thrown from a remote invocation on the same process.  It is not caused on a local invocation on the same process, or a remote invocation between separate processes.  

The following piece of code in the the privateInvoke method of the StubInvocationhandlerImpl class may cause the issue.  Because a Throwable instance is newly created here, then the copied instance is not handled as the original one afterward.

```
} catch (InvocationTargetException ex) {
Throwable mex = ex.getCause() ;
// mex should never be null, as null cannot be thrown
Throwable exCopy = (Throwable)Util.getInstance().copyObject(mex,orb);
if (dmm.isDeclaredException( exCopy ))
throw exCopy ;
```

## Steps to reproduce
1. Unzip [tp.zip](https://github.com/javaee/glassfish/files/1110947/tp.zip)
2. Rename *.ba to *.bat
3. Run the command
cd D:\glassfish4\glassfish\bin asadmin create-domain --nopassword=true mydomain1 asadmin start-domain mydomain1 asadmin deploy D:\work\tp\test.war
4. Access TestServlet
http://localhost:8080/test/TestServlet
5. See the results
[TestLocal] shows the stacktrace whle [TestRemote] does not.

**Comment by russgold** [comment]
I am able to reproduce the issue. I see no reason to believe that this is a regression. The most likely cause relates to serialization of responses, as code would need explicitly to serialize and deserialize the stack associated with an exception.

**Comment by russgold** [comment]
There's a bit of a problem with this test:

`			writer.println("[TestRemote]");
			writer.println("Throwable:" + t.toString());
			writer.println("Stack trace:");
			if (t.getStackTrace().length > 0) {
				for (StackTraceElement elem : t.getStackTrace()) {
					System.err.println("  " + elem.toString());
				}
			}
`

Note that you need to print to writer to generate servlet output, but you are actually writing the stack trace to System.err.

**Comment by russgold** [comment]
With the corrected test servlet, I can confirm that it is copying the exception in the above code that is causing the problem. It is not clear to me what value there is in doing this particular copy, as the exception is not serialized after this operation. Removing it and throwing the target exception preserves the stack trace. 

I will apply this change to the latest ORB code, pick it up in Glassfish and see if it breaks anything.

**Comment by russgold** [comment]
Fixed in ORB with:
commit 5a0d9bbc80a2265e151a07f56b571317a260cfaf
Author: Russell Gold <russell.gold@oracle.com>
Date:   Thu Jul 13 15:25:54 2017 -0400

    glassfish-21945 stop copying exception from call before rethrowing
