### ISSUE TITLE
Shoal GMS includes a reference to org.glassfish.grizzly.utils.LinkedTransferQueue.  This should be java.util.concurrent.LinkedTransferQueue

### ISSUE THREAD

**Issue by rlubke** [javaee/glassfish#22013]
Grizzly 2.4.0 has removed 3rd party collection classes since it now requires JDK8.
Specifically, org.glassfish.grizzly.utils.ConcurrentHashMapV8 and org.glassfish.grizzly.utisl.LinkedTransferQueue.

These classes were added in order to get better performance on JDK6 and 7 VMs.

After attempting to integrate grizzly-2.4.0-beta9, the Web HA tests began to fail.  I've traced the problem down to the missing org.glassfish.grizzly.utisl.LinkedTransferQueue class.

> ~/f/shoal   master   ag LinkedTransferQueue
>gms/impl/src/main/java/com/sun/enterprise/mgmt/transport/grizzly/grizzly2/ConnectionCache.java
>54:import org.glassfish.grizzly.utils.LinkedTransferQueue;
>185:                new LinkedTransferQueue<Connection>();

This import should be changed to java.util.concurrent.

A new integration of Shoal should probably be performed.  

## Environment Details
* GlassFish Version (and build number):
* JDK version:
* OS:
* Database:

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

Update nucleus/pom.xml and set the grizzly version to 2.4.0-beta9.  Run the web/ha devtests.  Observe a failure.

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

This is preventing me from integrating the latest release of Grizzly upon which is blocking several servlet issues.

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by edburns** [comment]
I have created a PR on shoal for this: <https://github.com/javaee/shoal/pull/121>.

I tested it and by building shoal locally, as version 1.6.51-SNAPSHOT, then updating glassfish/nucleus/pom.xml to update the shoal version to be that version, and also updating the Grizzly version to be 2.4.0-beta10.  I rebuilt GlassFish.  The ha/sessionFailover test passed.

**Comment by edburns** [comment]
I need someone to release Shoal 1.6.51 and integrate it, which I think
should be done under this issue 22013.
