### ISSUE TITLE
Bug 21738 has been marked as "Closed" but not fixed

### ISSUE THREAD

**Issue by tak-9** [javaee/glassfish#22024]
## Environment Details
* GlassFish Version (and build number): glassfish 5.0 b09 07_11_2017
Downloaded from this URL
http://download.oracle.com/glassfish/5.0/nightly/glassfish-5.0-b09-07_11_2017.zip
* JDK version: 1.8.0_131
* OS: Windows 2012
* Database:

----------
## Problem Description
I have recently received notification that the bug ticket #21738 has been "Closed". Today, I have downloaded the latest version of Glassfish 5.0 b09 July 11 2017 from the above URL and tested it.   However, I found that this bug has not been fixed yet.

## Number of Stateful session beans in Passive state is not updated (always 0) in Jconsole  #21738 

As you see in the above bug ticket, two files **StatefulSessionContainer.java**
 and **StatefulSessionBeanStatsProvider.java** need to be modified.

I have checked your source code repository. As far as I can see in the following repository, only one of these two files have been modified. 

- https://github.com/javaee/glassfish/blob/master/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatelessSessionContainer.java (Not fixed) 
- https://github.com/javaee/glassfish/blob/master/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/monitoring/stats/StatefulSessionBeanStatsProvider.java (Fixed) 

@srinivaskrishnan 
Please confirm it with the latest version and fix this bug again. Thank you.

**Comment by yaminikb** [comment]
@tak-9 Thanks for reporting back.

**Comment by srinivaskrishnan** [comment]
The fix is in 
https://github.com/javaee/glassfish/blob/master/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/containers/StatefulSessionContainer.java

but u are looking into StatelessSessionContainer.java.

**Comment by srinivaskrishnan** [comment]
Downloaded the latest build (http://download.oracle.com/glassfish/5.0/nightly/glassfish-5.0-b09-07_11_2017.zip). Able to see the passivecount to 600 with a restart of the server. Please check are you able to see the fix with a restart after accessing the url 'http://localhost:8080/StatefulBeansTest/MyServlet?count=600'.

U should see passivecount-current values from asadmin,

$ ./asadmin get -m  server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount*


server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.dotted-name = server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-current = 1200
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-description = Number of stateful session beans in Passive state
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-highwatermark = 1200
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-lastsampletime = 1499840647178
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-lowerbound = 0
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-lowwatermark = 0
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-name = PassiveCount
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-starttime = 1499840233642
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-unit = count
server.applications.StatefulBeansEAR.StatefulEJB\.jar.PassivationBean.passivecount-upperbound = 9223372036854775807

Will debug why restart is required.

**Comment by tak-9** [comment]
I was looking at the wrong file (StatelessSessionContainer.java and StatefulSessionContainer.java) when I posted the last message. I'm sorry about the confusion. 


I have checked the value again after restarting Glassfish. As you have suggested, I am seeing the passivecount is changed to 600 after restarting Glassfish.

**Comment by srinivaskrishnan** [comment]
While debugging it was found that some of probe listener registrations failed during startup it was somewhat similar to #21915. After updating the local branch with the master branch which has the fix for #21915 this issue got fixed. Now without restarting we get non zero value for passivecount. So requesting the filer to check with the latest promoted build at this link(https://javaee.github.io/glassfish/).)

**Comment by srinivaskrishnan** [comment]
Use the following binary for testing, I downloaded and tested it works.

http://download.oracle.com/glassfish/5.0/nightly/latest-glassfish.zip

**Comment by srinivaskrishnan** [comment]
Closing this issue as it is fixed.

**Comment by tak-9** [comment]
I have confirmed the issue has been fixed. Thank you.
