### ISSUE TITLE
Do not create EJB with default class name if deployment descriptor has an entry

### ISSUE THREAD

**Issue by mskdeepak-oracle** [javaee/glassfish#22075]
According to EJB 3.0 spec - "If the enterprise bean’s name is not explicitly specified in metadata 
 annotations or in the deployment descriptor, it defaults to the unqualified name of the bean class."

Currently, Glassfish creates an EJB with the default class name in this following case: name is not specified with the annotation and a corresponding entry exists in the ejb-jar.xml

**Comment by mskdeepak-oracle** [comment]
Closing the issue as it is not a spec compliance issue.  Adding an annotation to the class is the same as adding another entry to the deployment descriptor with a name corresponding to the annotation (explicit or defaulted).

**Comment by amykang2020** [comment]
Based on a discussion from Java EE spec lead/Java EE architect,  the EJB 3.2 section 14.2 p349 "Enterprise bean’s name" needs a clarification, see https://github.com/javaee/ejb-spec/issues/134
