### ISSUE TITLE
Error when creating new JDBC Connection Pool in GlassFish

### ISSUE THREAD

**Issue by CBradley97** [javaee/glassfish#22110]
When I try and create a new jdbc connection pool an error comes up when I click on create which says 'HTTP Status 500 - Internal Server Error
type Exception report
messageInternal Server Error
descriptionThe server encountered an internal error that prevented it from fulfilling this request.
exception
java.lang.IllegalStateException: getOutputStream() has already been called for this response
note The full stack traces of the exception and its root causes are available in the GlassFish Server Open Source Edition 4.1.1 logs.'

GlassFish 4.1.1
JDK version: 1.8.0_111
OS: Windows

This is a project I am doing for University and I need to complete it by the end of next month so any help would be appreciated.

**Comment by yaminikb** [comment]
@CBradley97 This is a known bug in 4.1.1 #21314 It was addressed in 4.1.2 and later. Please use the latest GlassFish 5.0:
http://download.oracle.com/glassfish/5.0/nightly/index.html

**Comment by yaminikb** [comment]
Closing since this issue is already fixed.
