### ISSUE TITLE
Task: Remove old JBI tests

### ISSUE THREAD

**Issue by delabassee** [javaee/glassfish#22113]
## Environment Details
* GlassFish Version (and build number): NA
* JDK version: NA
* OS: NA
* Database: NA

----------

## Problem Description

I assume the [JBI tests](https://github.com/javaee/glassfish/tree/master/appserver/tests/jbi) (Java Business Integration / JSR 208) are legacy stuff and aren't used anymore. If so, it would be nice to remove them when time permits (low priority task).

**Comment by kokil12** [comment]
Cleaned the jbi tests as a part of this PR https://github.com/javaee/glassfish/pull/22424

**Comment by kokil12** [comment]
The PR has been merged. Hence, closing the task
