### ISSUE TITLE
"Max Post Size" listener setting

### ISSUE THREAD

**Issue by brasta78** [javaee/glassfish#22202]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): 4.1 , 5.0 build1, latest web 5.0 (build java_re-private downloaded 2017-08-10) 
* JDK version: 8 update 122 64bit
* OS: Windows 10 64bit
* Database:

----------

## Problem Description
trying to upload photo ~ 2MB in Primefaces 6.1  p:textEditor componnent I always get error:

Warning:   GRIZZLY0205: Post too large
Severe:   java.lang.IllegalStateException: GRIZZLY0205: Post too large

Setting "Max Post Size" to -1 or any >1mljn value in Configurations - server config - Network Config - Network Listeners - http-listener-1 doesn't help.

project war for testing: 
https://drive.google.com/drive/folders/0BwNKQy9e9LXhbmxNTm9iWjRDeDA?usp=sharing 
## Steps to reproduce
simply press "image" icon, select image above 2MB and press "Submit"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by rlubke** [comment]
The setting you actually want for x-www-form-urlencoded content is max-form-post-size.  I'm not sure why this isn't exposed via the UI, but you can configure it using asadmin set.

I would recommend logging an enhancement against the UI to have this property expose.
