### ISSUE TITLE
Set-Cookie header: folding several cookies in one header not working on Firefox (HTTPS + HTTP/2.0 only)

### ISSUE THREAD

**Issue by xsistema** [javaee/glassfish#22208]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): glassfish-5.0-web-b16-07_31_2017
* JDK version: 1.8.0_141-b15
* OS: Windows 10 / Solaris 11.3
* Database: HyperSQL

----------

## Problem Description
I noticed that Glassfish5 web server sends responses with only one `Set-Cookie` header, which contains several cookies. When I looking with firebug, I can see that they are separated by unknown character. Anyway - the Firefox reads only the first cookie. I'm using Java Servlets 3.1. The same problem exists on Windows 10 64-bit, and Solaris 11.3 (Intel CPU). If I analyze the responses from different web servers - I can see that cookies, which are sent in one `Set-Cookie` header, are separated by new line characters. I've noticed that this happens only on HTTPS connections. Tried the same web application to run on Tomcat 9 web server - cookies are separated by new line character, it's working like expected...

I have uploaded some images and more information [here](https://stackoverflow.com/questions/45643689/set-cookie-header-in-glassfish-5-folding-several-cookies-in-one-header-not-work).

New discovery - it is only related to HTTP2 protocol. If I disable in Firefox HTTP2 by `network.http.spdy.enabled.http2` in `about:config` - the cookies are set as expected using http and https.

## Steps to reproduce
Set several cookies in HTTPS response using HTTP/2.0 protocol.

## Impact of Issue
Can not use more than one cookie in secure HTTPS response.

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by jsyxin** [comment]
When a header has multiple values, this problem is also existed.
Seems like this is a grizzly problem. In org.glassfish.grizzly.http2.EncoderUtils.encodeUserHeaders(), it always use '\u0000' as delimiter when there are multiple values for one header name.

**Comment by rlubke** [comment]
It looks like this code is from an earlier draft version of the the HTTP/2 RFC.  It should be re-worked based on the current RFC language.

**Comment by rlubke** [comment]
@xsistema Can you please try this JAR [1] and verify resolution?

This would go in GF_HOME/modules.  You'll probably want to clear out the domain's OSGi cache as well before restarting (rm -rf GF_HOME/domains/<domain_name>/osgi-cache/*)

[1] https://www.dropbox.com/s/u39sfe27woe6r0e/nucleus-grizzly-all.jar?dl=0

**Comment by xsistema** [comment]
Yes, I can confirm that now its working like it should be :) Thanks indeed for this quick fix!
