### ISSUE TITLE
GF report a wrong build number since Promotion 20

### ISSUE THREAD

**Issue by delabassee** [javaee/glassfish#22217]
## Environment Details
* GlassFish Version (and build number): GF5 Promoted Build 20 (full platform)
* JDK version: 1.8.0_144
* OS: OS X 10.11.6 
* Database: NA

----------

## Problem Description

GF5 reports a wrong build number in Promotion 20.

## Steps to reproduce

Using b20, "Admin Console", "About" reports "GlassFish Server Open Source Edition 5.0 (**build 12**)"
I just tested on b19 and b17, they are reporting their correct respective build number.

## Impact of Issue

This doesn't impact me but I want to make sure that this doesn't hide a more important issue.

**Comment by arindam-bandyopadhyay** [comment]
@delabassee 
I just tested. It's showing **build20**. Please refer the attached screenshot. 
![admingui](https://user-images.githubusercontent.com/9819737/29405534-c7c21c50-835b-11e7-9f2a-365d211e374a.png)

**Comment by delabassee** [comment]
Sorry, the error should be on my side then. I probably have too many GF5 installed!
