### ISSUE TITLE
GF-container inject's default resouce insead of my custom resource

### ISSUE THREAD

**Issue by kha-ruslan** [javaee/glassfish#22245]
* GlassFish Server Open Source Edition  5.0  (build java_re-private)
* JDK version: 1.8.0_144
* OS: Win-10
* Database: MSSQL

----------

I trying to use my resource to connect to MSSQL DB, but i see that GF injecting default resource. Then i direct default JDBC Resource to my custom ConnectionPool and application work fine.

Warning:   RAR5038:Unexpected exception while creating resource for pool DerbyPool. Exception : javax.resource.spi.ResourceAllocationException: Connection could not be allocated because: java.net.ConnectException : Ошибка соединения с сервером localhost на порту 1 527 с сообщением Connection refused: connect.
Warning:   RAR5117 : Failed to obtain/create connection from connection pool [ DerbyPool ]. Reason : com.sun.appserv.connectors.internal.api.PoolingException: Connection could not be allocated because: java.net.ConnectException : Ошибка соединения с сервером localhost на порту 1 527 с сообщением Connection refused: connect.
Warning:   RAR5114 : Error allocating connection : [Error in allocating a connection. Cause: Connection could not be allocated because: java.net.ConnectException : Ошибка соединения с сервером localhost на порту 1 527 с сообщением Connection refused: connect.]
Severe:   java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: java.net.ConnectException : Ошибка соединения с сервером localhost на порту 1 527 с сообщением Connection refused: connect.
	at com.sun.gjc.spi.base.AbstractDataSource.getConnection(AbstractDataSource.java:121)
.................................

Injecting resource:
![image](https://user-images.githubusercontent.com/31272241/29657772-5da6bc2a-88c1-11e7-9517-fbd9f11f6f12.png)
Pool ping:
![image](https://user-images.githubusercontent.com/31272241/29657818-857d9e4e-88c1-11e7-8714-dc573a7e819e.png)
Resource config:
![image](https://user-images.githubusercontent.com/31272241/29657861-ad9615aa-88c1-11e7-9afb-21f55f1fb69c.png)
web.xml:
![image](https://user-images.githubusercontent.com/31272241/29657935-e5c958c4-88c1-11e7-8f8b-44df924ee2f9.png)

I want to use my several custom resources instead of default resource.

What I doing wrong?

**Comment by kha-ruslan** [comment]
This problem is actual for the GF 5.0 b22 (latest build) too.

**Comment by mskdeepak-oracle** [comment]
I think you are using the wrong syntax here. Can you try the following?
```
@Resource(name = "xxx", lookup = "jdbc/MSSQLResource")
private javax.sql.DataSource ds;
```

The name attribute defines a resource in the `java:comp/env` namespace. In this case the resource being created would be `java:comp/env/jdbc/MSSQLResource`. Since you are not specifying the lookup element, Glassfish is linking the default resource to it. You can also specify the jndi name using a glassfish-web.xml deployment descriptor. So, I think adding a runtime DD would be another option for you.

**Comment by kha-ruslan** [comment]
Thank you for reply. It motivate me to do some experiment. I have tryed combinattions as followings:

1. @Resource(name = "jdbc/MSSQLResource", lookup = "java:global")
2. @Resource(name = "jdbc/MSSQLResource", lookup = "java:comp")
and (just in case)
3. @Resource(name = "java:global", lookup = "jdbc/MSSQLResource")
4. @Resource(name = "java:comp", lookup = "jdbc/MSSQLResource")

In 1 case result is:
java.lang.IllegalArgumentException: Can not set javax.sql.DataSource field servlets.LoginServlet1.dsc to com.sun.enterprise.naming.impl.SerialContext

in 2 case is:
org.glassfish.deployment.common.DeploymentException: JNDI lookup failed for the resource: Name: [java:module/env/jdbc/MSSQLResource], Lookup: [java:comp], Type: [javax.sql.DataSource]

In 3:
java.lang.IllegalArgumentException: Can not set javax.sql.DataSource field servlets.LoginServlet1.dsc to com.sun.enterprise.naming.impl.SerialContext

In 4:
java.lang.IllegalArgumentException: Can not set javax.sql.DataSource field servlets.LoginServlet1.dsc to com.sun.enterprise.naming.impl.JavaURLContext

But nothing is worked.

**Comment by kha-ruslan** [comment]
I thought that `name` is resource name, and `lookup` is where to search the resource, but I was wrong.
![image](https://user-images.githubusercontent.com/31272241/29778706-ed9c557e-8c18-11e7-83c6-f98b577c0cf4.png)
` @Resource(lookup = "jdbc/MSSQLResource")` is working code.
