### ISSUE TITLE
Cant start Glassfish 5 / JDK 9

### ISSUE THREAD

**Issue by ghostidentity** [javaee/glassfish#22278]
An error occurred while trying to start the server  by executing"startserv.bat" the same thing happened when using asadmin.

The script terminated immediately, but when starting it through CMD it says nullpointer exception.

com.sun.enterprise.modulel.commo_impl.AbtractModulesRegistryImpl.InitializeServerLocator....

Do glassfish 5 supports java 9 ?

## Environment Details
* Glassfish 5
* JDK  9
* Windows 10
* Database: NA

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by ghostidentity** [comment]
Nvm guys! i just read the install instruction. I thought it supports java 9 for this release. thanks! this issue can be closed.

**Comment by arindam-bandyopadhyay** [comment]
Duplicate to #22130. Closing it
