### ISSUE TITLE
JSP issues are not assigned

### ISSUE THREAD

**Issue by tsyamamoto** [javaee/glassfish#22275]
I reported jsp issues before.
https://github.com/javaee/javaee-jsp-api/issues

https://github.com/javaee/javaee-jsp-api/issues/56
https://github.com/javaee/javaee-jsp-api/issues/55
https://github.com/javaee/javaee-jsp-api/issues/54
https://github.com/javaee/javaee-jsp-api/issues/53

However, it seems that no one has been assigned yet.
Please check.
Otherwise, should I create issues about jsp in glassfish repository?

**Comment by ruolli** [comment]
All these 4 issues were addressed, closing this tracking issue.
