### ISSUE TITLE
Is there a way to find out which application in glassfish is creating more file descriptors ?

### ISSUE THREAD

**Issue by suresh-wipro** [javaee/glassfish#22277]
## Environment Details
* GlassFish Version (and build number): GlassFish Server Open Source Edition 3.1.2.2 (build 5)
* JDK version: 

java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) Client VM (build 24.51-b03, mixed mode)

* OS: Oracle Solaris 11.3 X86
* Database: NA

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"

We are using glassfish 3.1.2.2 (build 5) to deploy 7 or 8 applications. In one such deployment we are seeing high number of file descriptors for glassfish. This number is between 5k to 10k. Once the file descriptor count reaches this count, the count will not come down. To see what exactly these file descriptors are pointing to, we took pfiles output of glassfish pid. What we saw are many number of extent files in glassfish transaction directory. i.e /opt/glassfish3/glassfish/domains/domain1/logs/server/tx/. 

Now, we know about default value of keypoint-interval being 65536 [ This should have been 2048 ] in glassfish 3 and its effect on number of extent files. 

What we want to know is : 

Can we enable some sort of logging in glassfish and find out who is creating more number of transactions and indirectly these extent files ? 

[//]: # "State if the problem is easily reproducible or happens intermittently"
Happens Intermittently.

[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"

This spike in FDs is seen whenever the server is rebooted. 
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
We are trying to find out which among the applications deployed on glassfish are creating more number of transactions in glassfish, thereby increasing the number of extent files and FDs. 

[//]: # "Please choose one each Type, Component, and Priority label"

Type : Query
Component : Glassfish 
Priority label : Medium.

**Comment by suresh-wipro** [comment]
[glassfishPfiles.zip](https://github.com/javaee/glassfish/files/1317443/glassfishPfiles.zip)

**Comment by suresh-wipro** [comment]
Hi All

If you want to have a look at pfiles output of glassfish pid, I have attached that file. 

Regards

Amogha

**Comment by suresh-wipro** [comment]
Hi All 

Can this be assigned to someone ? Can we get some pointers on this situation ?

Regards

Amogha

**Comment by delabassee** [comment]
GF 3.1.x is quite old! This issue tracker is for recent version of GlassFish, i.e. GF 5.
I would suggest to post this kind of question to the [GlassFish group](https://javaee.groups.io/g/glassfish) instead.
