### ISSUE TITLE
Glassfish 5.0 Embedded

### ISSUE THREAD

**Issue by Boosted2003** [javaee/glassfish#22283]
Hello Everyone!

I was curious if there is a schedule for the release of glassfish 5 embedded?

Thank you,
James

## Environment Details
* GlassFish Version (and build number): 5.0
* JDK version: Java 8 Update 144 
* OS: RHEL 7.3
* Database: NA

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by romain-grecourt** [comment]
GlassFish embedded 5.0 was released, see http://repo1.maven.org/maven2/org/glassfish/main/extras/glassfish-embedded-all/5.0/

Are you instead referring to the Maven plugin ? (http://repo1.maven.org/maven2/org/glassfish/embedded/maven-embedded-glassfish-plugin/)

**Comment by Boosted2003** [comment]
The first link is what I was looking for!
