### ISSUE TITLE
Build from sources fails on linux

### ISSUE THREAD

**Issue by dmitrymozheyko** [javaee/glassfish#22290]
## Environment Details
* GlassFish Version (and build number): 5.0.1
* JDK version: Java version: 1.8.0_144, vendor: Oracle Corporation
* OS: CentOS Linux release 7.4.1708 (Core)
* Database: -

----------

## Problem Description
Maven build on Linux Machine fails on TESTS phase:

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.glassfish.grizzly.config.GrizzlyConfigTest
Oct 09, 2017 8:29:41 PM org.glassfish.grizzly.http2.Http2AddOn setup
WARNING: TLS ALPN (Application-Layer Protocol Negotiation) support is not available. HTTP/2 support will not be enabled.
Oct 09, 2017 8:29:41 PM org.glassfish.grizzly.http2.Http2AddOn setup
WARNING: TLS ALPN (Application-Layer Protocol Negotiation) support is not available. HTTP/2 support will not be enabled.
Oct 09, 2017 8:29:41 PM org.glassfish.grizzly.http2.Http2AddOn setup
WARNING: TLS ALPN (Application-Layer Protocol Negotiation) support is not available. HTTP/2 support will not be enabled.
Oct 09, 2017 8:29:41 PM org.glassfish.grizzly.http2.Http2AddOn setup
WARNING: TLS ALPN (Application-Layer Protocol Negotiation) support is not available. HTTP/2 support will not be enabled.
Oct 09, 2017 8:29:45 PM org.glassfish.grizzly.config.GenericGrizzlyListener configureTransport
WARNING: Element, selection-key-handler, has been deprecated and is effectively ignored by the runtime.
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.56 sec <<< FAILURE!
==============================================
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T22:39:06+03:00)
Maven home: /opt/glassfish/apache-maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_144/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-693.2.2.el7.x86_64", arch: "amd64", family: "unix"

## Steps to reproduce

git clone https://github.com/javaee/glassfish.git
cd glassfish
mvn install

## Impact of Issue
I can't build last version on my server(downloads and autobuild folders on site are empty)

**Comment by romain-grecourt** [comment]
This is most likely a transient error, unless you can reproduce it every time you run the build.
FYI all tests must be passing for anything to be merged into master :)

1. Please include the content of the surefire reports for the failing tests.

2. Your building off master, please include the current commitId of the HEAD (``git rev-parse HEAD``)

3. You can skip the tests (http://maven.apache.org/plugins-archives/maven-surefire-plugin-2.12.4/examples/skipping-test.html)

4. Or you can download a nightly build (http://download.oracle.com/glassfish/5.0.1/nightly/index.html, but 5.0.1 just started and nightlies haven't been published yet)
