### ISSUE TITLE
Glassfish 5 dns redirect problem

### ISSUE THREAD

**Issue by lymychm** [javaee/glassfish#22291]
I have glassfish 5 and ear file deployed on it, where i have a web aplication on ejb 3 + jsf 2. And after any redirect on my website i'm getting something like this url in my browser(in any browser all version each), https://04c9734f3a71/, this problem only in glassfish 5, on glassfish 4.1 or 4.1.2, everithing works fine.

## Environment Details
* GlassFish Version (and build number): 5 build 25
* JDK version: 1.8.0.144-0.b01.el7_4
* OS: oraclelinux:latest or ubuntu 16
* Database: postgresql 9.5

**UPDATE**: after reinstall server, after any redirect/forward in my web app i'm getting  redirected to my local ip address of the server, any idea why?

**UPDATE 2**: redirect in my code:

via commandLink 
`FacesContext.getCurrentInstance().getExternalContext().redirect(FacesContext.getCurrentInstance().getExternalContext().getRequestContextPath() + pagePath);`

also after 
` <form action="j_security_check" method="post">...</form>` submit

**UPDATE 3** I have found that this problem occurs in https protocol but without ssl certificate, but still in Glassfish 4 works without ssl certificate

**Comment by Shedyk** [comment]
Hi @lymychm , where you able to find a workaround for this ? 
I'm having the same challenge using the default self-singed cert for HTTPS. 
I have a redirect in my welcome file and I get this `localhost sent an invalid response.
ERR_INVALID_REDIRECT` error.

**Comment by mydeadlyvenoms** [comment]
@Shedyk this might help you https://github.com/payara/Payara/issues/2614
E.g., try to disable HTTP/2 on your http(s) listener.
