### ISSUE TITLE
Glassfish5 and SQL Server creation of connection pool SSL error

### ISSUE THREAD

**Issue by trinidadmarcelo** [javaee/glassfish#22367]
## Environment Details
* GlassFish Version (and build number): 5.0 (build 25)
* JDK version: jdk1.8.0_152
* OS: Windows 10
* Database: SQL Server 2012

----------

## Problem Description
When creating a connection pool I have the following error: Ping Connection Pool failed for "mssql". The connection could not be allocated: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "Unsupported curveId: 29". ClientConnectionId: b89fd96e-a8c7-4948-89a1-b64c3f7d2825 Please check the server.log for more details.

The problem is easily reproducible

[//]: # "Include stack traces or command outputs"

## Steps to reproduce
Copy mssql-jdbc-6.3.4.jre8-preview.jar file to {GLASSFISH_ROOT}\glassfish\lib
Start glassfish server from {GLASSFISH_ROOT}\glassfish\bin\startserv.bat
Configure JDBC Connection Pool from http://localhost:4848 with following values :

Pool Name: mssql
Resource Type: javax.sql.DataSource
Data Source Class Name:	com.microsoft.sqlserver.jdbc.SQLServerDataSource
Ping	Enabled

In additional properties used following properties

user
password
databaseName
serverName

Then in General tab, clic on Ping button to test the connection.

## Impact of Issue
Can't migrate from version 4.1 to 5 due to this issue

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by gaudinnicolas** [comment]
Hi,
Facing exactly the same issue on 

    GlassFish Version (and build number): 5.0 (build 25)
    JDK version: jdk1.8.0_151
    OS: **Windows 10**
    Database: SQL Server 2008R2, 2012, 2014

mssql-jdbc-6.2.2.jre8.jar

A workaround is to set the JVM option (but with security hole!!):
<jvm-options>-Dcom.sun.net.ssl.enableECC=false</jvm-options>

Hope this helps and will lead you quickly to a fix....
Cheers

**Comment by trinidadmarcelo** [comment]
Hello @gaudinnicolas, it works!

I appreciate your help, now I can continue with my tests until version 5.0.1 solves this

Thanks

**Comment by BrianKnoblauch** [comment]
The workaround does not appear to work on Windows Server platforms.  Any other workarounds for those OS or am I stuck waiting for the  5.0.1 release?
