### ISSUE TITLE
javax.resource needs modified javax.transaction import/export

### ISSUE THREAD

**Issue by sdfelts** [javaee/glassfish#22467]
The new javax.transaction api jar now has a version of 1.3 and has removed the javax.transaction.xa classes.  The javax.resource jar needs modified import and export statements.

## Environment Details
* GlassFish Version (and build number): 5.0.1
* JDK version: 1.8
* OS: NA
* Database: NA

----------

## Problem Description
See above.

## Steps to reproduce
Build glassfish with the new javax.transaction-api 1.3 jar file.

## Impact of Issue
GF won't build with the new jar.

**Comment by yaminikb** [comment]
The issue has been addressed in new version of javax.resource 1.7.1 #22480
